### ISSUE TITLE
Startup login problems

### ISSUE THREAD

**Issue by zls1988** [amir-zeldes/rstWeb#86]
After deploying a rstweb as a docker container, I tried to log in as admin (with default pass) and got a 500 error.

Error in /var/log/apach2/error.log:
[Mon Dec 07 09:56:29.290367 2020] [http:error] [pid 12:tid 139853656221440] [client 172.17.0.1:45420] AH02429: Response header name '<!--' contains invalid characters, aborting request, referer: https://rstweb.mydimain.net/rstweb/open.py

**Comment by amir-zeldes** [comment]
Hi - I think the underlying error is something different. Probably the error triggers cgitb to print a message in nice human readable html in the web interface, which leads to the string '<!--' in the header, but that is not the actual, initial error, so it's a little hard to guess what the actual problem is.

@lgessler any good ideas on how to debug this inside docker? If this were just python on apache I'd say to comment out [this line](https://github.com/amir-zeldes/rstWeb/blob/master/open.py#L27) and see what the error message is, or else to put `print(Content-Type: text/html\n\n)` just before that line and actually use cgitb to see the error.

**Comment by IHumonen** [comment]
I am very sorry, but has there been any progress on this problem?
@zls1988
@amir-zeldes
@lgessler

**Comment by jimyaghi** [comment]
i'm seeing the same error on apache server. i did the config as was explained in the docs. i'm running on https

**Comment by amir-zeldes** [comment]
@jimyaghi Python 2/3 should both work. From your description it sounds like it might have been a permissions issue, but I'm glad it's resolved either way. The 'header contains invalid characters' issue can be circumvented by editing the script triggering the error (e.g. `open.py`), and typing:

`print("Content-Type: text/html\n\n")`

before all of the imports. That will cause the header to be valid, and then you should be able to see what the actual error message is. Unfortunately I can't reproduce the error from @zls1988 , so unless you can get it to print out a more informative error I'm afraid I don't have a good idea on how to figure out what is specifically wrong. 

If it's crashing already just from logging in, that sounds like it could be a permissions issue (the user file is edited to reflect last login when logging in, though I think permissions problems shouldn't happen in Docker) or maybe some incompatible library or locale versions, though again it's a little surprising inside a Docker container.

**Comment by jimyaghi** [comment]
for python2 all things work normally and are resolved with permission fixes. you need to add +x permission to the open.py and admin.py scripts. you must ensure they are owned by www-data

However in python3 this is the error (thanks for the tip to add Content-Type header)

![image](https://user-images.githubusercontent.com/15869425/103440383-3b85a200-4c45-11eb-8612-7b4799eccacc.png)

**Comment by amir-zeldes** [comment]
Hmm, in local mode under windows it works with both python 3.6 and 3.8. However in server mode it will invoke dataenc.py, which results in an error. Also, python 3.8 doesn't support time.clock:

```
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

I think this should be relatively easy to fix.

**Comment by amir-zeldes** [comment]
OK, I just pushed an update to dev which should fix the version compatibility. It now works for me using Python 3.5 in server mode on a RHEL server. @jimyaghi can you take a look and see if the code in dev works on your python 3 setup out of the box?
